# Generated by Django 3.2.3 on 2021-06-03 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors.guest'),
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_treated', models.BooleanField()),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitors.guest')),
            ],
        ),
    ]
